# -*- coding: utf-8 -*-
"""Project 1 – Student Performance Analyzer.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zxk0wbFCUCGpu-XG2cN6dFGJuVh8msTh
"""

def calculate_grade(percentage):
    if percentage >= 90:
        return "A+"
    elif percentage >= 80:
        return "A"
    elif percentage >= 70:
        return "B"
    elif percentage >= 60:
        return "C"
    elif percentage >= 50:
        return "D"
    else:
        return "Fail"

# Taking student name input
student_name = input("Enter Student Name: ")
marks = []

# Taking marks for 5 subjects
for i in range(1, 6):
    mark = float(input(f"Enter marks for Subject {i}: "))
    marks.append(mark)

# Calculating total
total = sum(marks)

# Calculating percentage
percentage = total / 5

# Calculating grade
grade = calculate_grade(percentage)

# Displaying final report card
print("\n========== REPORT CARD ==========")
print("Student Name :", student_name)

for i in range(5):
    print(f"Subject {i+1} Marks :", marks[i])

print("---------------------------------")
print("Total Marks  :", total)
print("Percentage   :", percentage, "%")
print("Grade        :", grade)